export const MONGO_DB_URI_KEY: string = 'MONGO_DB_URI',
  PORT_KEY: string = 'PORT',
  DEFAULT_PORT: string = '8080',
  INTERNAL_SERVER_ERROR: string = 'Internal Server Error',
  GSHEETS_API_VERSION = 'v4',
  GSHEETS_AUTH_URL: string = 'https://www.googleapis.com/auth/spreadsheets',
  DEFAULT_RANGE: string = 'A:Z',
  ROW: string = 'ROW',
  NO_DATA_IN_RANGE: string = 'No data found in that range',
  SHEET_NOT_FOUND: string = 'Sheet not found',
  UPDATED_SUCCESSFULLY: string = 'updated successfully',
  DELETED_SUCCESSFULLY: string = 'deleted successfully',
  ADDED_SUCCESSFULLY: string = 'added successfully',
  MISSING_GSHETS_PARAMS: string =
    'Missing required parameters [spreadsheetId, range, data] make sure to pass all required parameters';
